### ISSUE TITLE
运行报错是啥原因啊

### ISSUE THREAD

**Issue by yejinson** [yongjiu8/unidbg-jd-sign#1]
<img src='https://s2.loli.net/2022/05/26/b4U23whduIMkvj5.png' title='quicker_110abb23-1728-4e72-8ce5-4fc78b188816.png' />
<img src='https://s2.loli.net/2022/05/26/pPR6r1hvJiQ2C5l.png' title='quicker_8475019d-cbe6-4214-8c26-250f19a3f429.png' />

**Comment by ghost** [comment]
只支持armeabi-v7a不支持arm64-v8a，有点遗憾

**Comment by yejinson** [comment]
> armeabi-v7a

用的就是armeabi-v7a不行啊

**Comment by yongjiu8** [comment]
使用jdk8编译即可 另外不支持64位so 只支持32位

**Comment by yejinson** [comment]
> 使用jdk8编译即可 另外不支持64位so 只支持32位

谢谢作者大大。
