### ISSUE TITLE
换了32位的jdk还是报错

### ISSUE THREAD

**Issue by hanjiangjiaolong** [yongjiu8/unidbg-jd-sign#5]
![image](https://user-images.githubusercontent.com/20113166/174929359-d04189fe-f708-47ac-8819-4753eef5ab35.png)

**Comment by hanjiangjiaolong** [comment]
环境 jdk8-32   apk 11.0.4  so:lib\armeabi-v7a

**Comment by yongjiu8** [comment]
这是要用32位的so 你用64的so就会报错 ，修改代码可以支持64
